In [3]:
import sys
from pathlib import Path

# Force notebook to recognize project root
import os
ROOT = Path(os.getcwd()).resolve().parents[0] # one level up from tests/
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

import pandas as pd
from src.inference_pipeline.inference import predict

# Load a few rows of already preprocessed data
sample_path = ROOT / "data/processed/cleaning_eval.csv"
df = pd.read_csv(sample_path).sample(5, random_state=42).reset_index(drop=True)

print("Input sample:")
display(df.head())

# Run inference
preds_df = predict(df)
print("✅ Predictions returned")
display(preds_df[["predicted_price"]].head())

Input sample:

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,...,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full,lat,lng
0,2021-07-31,258528.0,259900.0,145.396160,140.979244,104.0,98.0,107.0,66.0,48.0,...,182900.0,10937.0,250.0,20604.0,20604.0,10007.0,255300.562038,cincinnati,NaN,NaN
1,2021-08-31,457000.0,429000.0,253.164135,257.973734,82.0,95.0,117.0,126.0,71.0,...,0.0,0.0,0.0,0.0,0.0,0.0,450603.296700,new york-newark-jersey city,NaN,NaN
2,2020-02-29,187250.0,202500.0,99.965760,109.198464,94.0,115.0,140.0,157.0,47.5,...,161000.0,31265.0,1746.0,52357.0,52357.0,27625.0,189474.969209,houston-pasadena-the woodlands,NaN,NaN
3,2020-06-30,517500.0,539900.0,217.805198,217.108051,6.0,11.0,11.0,14.0,68.0,...,531100.0,1251.0,30.0,1991.0,1991.0,1156.0,504649.454265,baltimore-columbia-towson,NaN,NaN
4,2021-07-31,749000.0,749400.0,349.226265,339.058053,113.0,112.0,140.0,60.0,18.0,...,591100.0,16826.0,681.0,31591.0,31591.0,14740.0,699558.033278,riverside-san bernardino-ontario,NaN,NaN

⚠️ Skipping lat/lng merge: already present in DataFrame.
✅ Dropped 0 duplicate rows (excluding date/year).
✅ Removed 0 rows with median_list_price > 19M.
✅ Predictions returned

   predicted_price
0    218091.921875
1    414128.937500
2    232263.640625
3    495610.000000
4    659299.625000